/* eslint-disable react/jsx-no-undef */
import '../styles/globals.css'
import React from 'react'
import Navbar from '../componants/Navbar'
import Head from 'next/head'



function MyApp({ Component, pageProps }) {
  return <>
      < Head>
        <title>BrokenOnesNFT</title>
        <meta name="By the BrokenOne For the BrokenOnes " content="Generated by create next app" />
        <link rel="icon" href="/heart.png" />
      </Head>
  
    <Navbar/>
    <Component {...pageProps} />
    </>
}

export default MyApp
